version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: build/Dockerfile
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    volumes:
      - ../configs/app.toml:/configs/app.toml
    command: [ "./api_server", "--config=configs/app.toml" ]
    depends_on:
      - db
    networks:
      antibrutforce:
        aliases:
          - app
  migrate:
    build:
      context: ..
      dockerfile: build/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: >
      goose -dir /migrations postgres "postgres://dbuser:dbpass@db:5432/dbname?sslmode=disable" up
    restart: "no"
    networks:
      antibrutforce:
        aliases:
          - migrate

  db:
    image: postgres:16.8-alpine3.21
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      antibrutforce:
        aliases:
          - db

networks:
  antibrutforce:

volumes:
  pgdata: