[logger]
level = "info"
format = "text"

[app]
host = "localhost"
#host = "0.0.0.0"
port = "8080"

[database]
#host = "db"
host = "localhost"
port = "5432"
dbname = "dbname"
user = "dbuser"
pass = "dbpass"